# =============================================================================
# PyForum Inventory
# Статический inventory файл
# Для добавления новых серверов — добавь IP в нужную группу
# =============================================================================

[dbservers]
pyforum-oracle9-pgsqldbserver ansible_host=192.168.56.20 ansible_ssh_private_key_file=/home/vagrant/.ssh/id_rsa_dbserver

[appservers]
pyforum-oracle9-appserver ansible_host=192.168.56.10 ansible_ssh_private_key_file=/home/vagrant/.ssh/id_rsa_appserver

# Общие настройки SSH для всех хостов
[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
