#!/bin/bash
# =============================================================================
# pyforum-provision-controlnode.sh
# Provision script for Ansible control node
# OS: Oracle Linux 9
# Run as: root (via Vagrant shell provisioner)
# Requires: dbserver, appserver, vaultnode must be running
# =============================================================================

set -e

echo "============================================"
echo "  PyForum Control Node Provisioning"
echo "  Host: $(hostname)"
echo "============================================"

# =============================================================================
# Install Ansible
# =============================================================================
echo ""
echo "==> [CTRL] Installing Ansible..."
dnf install -y epel-release
dnf install -y ansible python3-pip
echo "==> [CTRL] Ansible installed: $(ansible --version | head -1)"

# =============================================================================
# Install hvac — Python client for HashiCorp Vault
# Required by community.hashi_vault Ansible collection
# =============================================================================
echo ""
echo "==> [CTRL] Installing hvac (Vault Python client)..."
pip3 install hvac
echo "==> [CTRL] hvac installed."

# =============================================================================
# Install community.hashi_vault Ansible collection
# =============================================================================
echo ""
echo "==> [CTRL] Installing community.hashi_vault collection..."
ansible-galaxy collection install community.hashi_vault
echo "==> [CTRL] community.hashi_vault installed."

# =============================================================================
# Copy SSH keys for dbserver and appserver
# Keys are generated by Vagrant and stored in .vagrant/machines/
# =============================================================================
echo ""
echo "==> [CTRL] Copying SSH keys..."
mkdir -p /home/vagrant/.ssh
cp /home/vagrant/pyforum/.vagrant/machines/dbserver/virtualbox/private_key  /home/vagrant/.ssh/id_rsa_dbserver
cp /home/vagrant/pyforum/.vagrant/machines/appserver/virtualbox/private_key /home/vagrant/.ssh/id_rsa_appserver
chmod 600 /home/vagrant/.ssh/id_rsa_dbserver
chmod 600 /home/vagrant/.ssh/id_rsa_appserver
chown vagrant:vagrant /home/vagrant/.ssh/id_rsa_dbserver
chown vagrant:vagrant /home/vagrant/.ssh/id_rsa_appserver
echo "==> [CTRL] SSH keys ready."

# =============================================================================
# Set Vault environment variables for the vagrant user
# These are needed by community.hashi_vault lookup when running playbooks
# =============================================================================
echo ""
echo "==> [CTRL] Setting Vault environment variables..."
echo ""                                         >> /home/vagrant/.bashrc
echo "# HashiCorp Vault"                        >> /home/vagrant/.bashrc
echo "export VAULT_ADDR=http://192.168.56.40:8200" >> /home/vagrant/.bashrc
echo "export VAULT_TOKEN=root"                  >> /home/vagrant/.bashrc
echo "==> [CTRL] VAULT_ADDR and VAULT_TOKEN added to .bashrc."

echo ""
echo "============================================"
echo "  [CTRL] Provisioning complete!"
echo "  Ansible: $(ansible --version | head -1)"
echo ""
echo "  Next steps:"
echo "  1. vagrant ssh controlnode"
echo "  2. cd /home/vagrant/pyforum/ansible"
echo "  3. ansible-playbook -i inventory/hosts.ini playbooks/dbserver.yml"
echo "  4. ansible-playbook -i inventory/hosts.ini playbooks/appserver.yml"
echo "============================================"
